import { useLang, type Lang } from "@/lib/lang";

export const copy = {
  de: {
    brand: "AEXUM",
    brandSub: "Aluminium Extrusions",
    nav: {
      products: "Profile",
      capabilities: "Leistungen",
      quality: "Qualität",
      rfq: "Anfrage",
    },
    topbar: "EU + UK  ·  EN 755 / EN 12020  ·  CE & UKCA",
    langDe: "DE",
    langEn: "EN",
    ctaPrimary: "Zeichnung anfragen",
    ctaSecondary: "Pressen & Legierungen",
    heroKicker: "Strangpresswerk · Göppingen  ·  UK Desk · Birmingham",
    heroTitle: "Stranggepresstes Aluminium für die Industrie Europas.",
    heroLead:
      "Sonderprofile und Serienteile aus 6xxx-Legierungen. Vom Werkzeug bis zur bearbeiteten, oberflächenfertigen Stange — geliefert in die EU und nach Großbritannien.",
    stats: [
      { value: "48.000 t", label: "Jahreskapazität" },
      { value: "18–45 MN", label: "Vier Pressen" },
      { value: "320 mm", label: "Umkreis Ø" },
      { value: "14 m", label: "max. Stangenlänge" },
    ],
    productsKicker: "Produktfamilien",
    productsTitle: "Profile, die in die Maschine passen — nicht umgekehrt.",
    productsLead:
      "Massiv, hohl, Steck- und Kühlkörperprofile. Wir pressen nach Ihrer Zeichnung oder aus unserem Katalog EN-AW 6060 / 6063 / 6005A / 6082.",
    families: [
      {
        title: "Maschinenbau-Nuten",
        body: "T-Nut 30 / 40 / 45 / 50, kompatibel zu gängigen Baukastensystemen. Sägen, entgraten, Gewinde, Beschichtung.",
      },
      {
        title: "Konstruktionshohlprofile",
        body: "Rechteck, Rund, Mehrkammer. Wandstärken ab 1,2 mm. Für Gestelle, Fahrwerke, Gehäuse.",
      },
      {
        title: "Kühlkörper & Leistungselektronik",
        body: "Lamellenprofile mit hohem Oberfläche-zu-Masse-Verhältnis. 6060-T6 und 6101 auf Anfrage.",
      },
      {
        title: "Sonderprofile",
        body: "Porthole- und Massivmatrizen. Erste Muster typisch 8–12 Wochen nach Werkzeugfreigabe.",
      },
    ],
    industriesKicker: "Abnehmerbranchen",
    industriesTitle: "Wo Aluminium lasttragend und maßhaltig sein muss.",
    industries: [
      { title: "Maschinen & Automation", body: "Gestelle, Linearachsen, Schutzumhausungen." },
      { title: "Nutzfahrzeuge & Schiene", body: "Leichtbau-Längsträger, Trittstufen, Dachholme." },
      { title: "Energie & E-Mobilität", body: "Batterieträger, Wechselrichter-Gehäuse, Sammelschienen." },
      { title: "Gebäude & Fassade", body: "EN 15088, Qualanod / Qualicoat, EN 1090 EXC2." },
      { title: "Fördertechnik", body: "Führungen, Seitenwangen, Rollenbahnen." },
      { title: "Medizin & Labor", body: "Saubere Legierungen, dokumentierte Chargen." },
    ],
    processKicker: "Ablauf",
    processTitle: "Von der Matrize bis zur Verladung.",
    process: [
      { step: "01", title: "Werkzeug", body: "Strömungssimulation, Matrizenbau im Haus oder bei Stammlieferanten." },
      { step: "02", title: "Presse", body: "Bolzen 7xxx-frei, 6xxx-Spektrum. Recken, Richten, Warmauslagern T5/T6." },
      { step: "03", title: "Bearbeitung", body: "CNC, Stanzen, Sägen, Gewinde, Verbundmontage." },
      { step: "04", title: "Oberfläche", body: "Eloxal, Pulver, mechanisch schleifen. Qualanod / Qualicoat." },
      { step: "05", title: "Versand EU + UK", body: "CE- und UKCA-konforme Dokumente. Konsignationslager Midlands." },
    ],
    qualityKicker: "Nachweis",
    qualityTitle: "Was Einkauf und QS sehen wollen.",
    qualityLead:
      "Werkszeugnisse 3.1, Chargenrückverfolgung, Erstbemusterung nach VDA / PPAP auf Anfrage. Duales Konformitätspaket für EU und Vereinigtes Königreich.",
    certs: [
      "ISO 9001",
      "ISO 14001",
      "IATF 16949",
      "EN 15088",
      "EN 1090 EXC2",
      "EN 755 / EN 12020",
      "Qualanod",
      "Qualicoat",
      "CE / UKCA",
    ],
    logisticsTitle: "Europa und UK, ohne Umwege in der Dokumentation.",
    logisticsBody:
      "Seit dem Brexit liefern wir mit getrennten Konformitätserklärungen. UK-Kommissionierung über Birmingham, EU-Direkt ab Göppingen. Incoterms FCA, DAP oder DDP — je nach Rahmenvertrag.",
    finalCtaTitle: "Zeichnung schicken. Wir sagen, ob sie pressbar ist.",
    finalCtaBody:
      "Technische Prüfung innerhalb von zwei Werktagen. Kein Vertriebsfolien-Pingpong.",
    footerNote: "AEXUM GmbH  ·  Presswerk Göppingen  ·  UK Desk Birmingham",
    footerLegal: "Musterentwurf für industrielle Kunden. Kein öffentliches Angebot.",
    productsPage: {
      kicker: "Profile & Legierungen",
      title: "Was wir pressen.",
      lead: "6xxx-Knetlegierungen nach EN 573. Maße und Grenzabmaße nach EN 755-9 bzw. EN 12020-2 für Präzisionsprofile.",
      alloysTitle: "Legierungen",
      alloys: [
        { name: "EN AW-6060", temper: "T5 / T6", use: "Architektur, Nutenprofile, Eloxalqualität" },
        { name: "EN AW-6063", temper: "T5 / T6", use: "Dünnwandige Hohlprofile, Sichtflächen" },
        { name: "EN AW-6005A", temper: "T6", use: "Tragende Konstruktionen, höhere Streckgrenze" },
        { name: "EN AW-6082", temper: "T6", use: "Hochfeste Bauteile, Fahrwerke, Maschinenbetten" },
        { name: "EN AW-6101", temper: "T6 / T7", use: "Stromschienen, Leitfähigkeit" },
      ],
      limitsTitle: "Technische Grenzen",
      limits: [
        { k: "Presskraft", v: "18 / 25 / 35 / 45 MN" },
        { k: "Umkreis", v: "bis 320 mm" },
        { k: "Wandstärke", v: "ab 1,2 mm, profilabhängig" },
        { k: "Länge", v: "bis 14.000 mm" },
        { k: "Gewicht/m", v: "0,15–28 kg/m" },
        { k: "Losgröße", v: "ab ca. 300 kg Wiederhol, 800 kg Neuwerkzeug" },
      ],
    },
    capabilitiesPage: {
      kicker: "Leistungen",
      title: "Mehr als die Presse.",
      lead: "Viele Einkäufer wollen nicht drei Lieferanten für Pressen, CNC und Eloxal. Wir fassen die Kette.",
      blocks: [
        {
          title: "Strangpressen",
          body: "Vier Pressen, eigene Reckanlage, Durchlauföfen für T5 und T6. Bolzenlager für 6060, 6063, 6005A, 6082.",
        },
        {
          title: "Zerspanung",
          body: "5-Achs-CNC, Sägezentren, Stanzen, Gewindeformen. Zeichnungsteile mit Erstbemusterung.",
        },
        {
          title: "Oberfläche",
          body: "Eloxal EV1–C35, Harteloxal, Pulver nach RAL, Trommelschleifen. Qualanod- und Qualicoat-geführt.",
        },
        {
          title: "Logistik EU + UK",
          body: "Wochenfahrplan DACH, Benelux, Norditalien, Polen. UK: wöchentliche Sammelverladung, UKCA-Satz beigelegt.",
        },
      ],
    },
    qualityPage: {
      kicker: "Qualität & Normen",
      title: "Messbar, nicht behauptet.",
      lead: "Prüfmittel überwacht, Labor für Härte, Leitfähigkeit, Schichtstärke. 3.1-Zeugnisse digital abrufbar.",
      items: [
        { title: "Maße", body: "EN 755-9. Optische Messzellen an der Säge. SPC auf Serienläufern." },
        { title: "Werkstoff", body: "Spektrometer je Charge. Homogenisierte Bolzen, dokumentierte Wärmenachbehandlung." },
        { title: "Bauprodukte", body: "EN 15088, Leistungserklärung, UKCA-Äquivalent für den britischen Markt." },
        { title: "Automotive", body: "IATF 16949, PPAP Level 3 auf Abruf, IMDS-Einträge." },
      ],
    },
    rfqPage: {
      kicker: "Anfrage",
      title: "Technische Anfrage.",
      lead: "Keine Pflichtfelder-Orgie. Was wir brauchen: Legierung oder Einsatz, grobe Geometrie, Menge, Lieferland.",
      company: "Firma",
      country: "Lieferland",
      name: "Ansprechpartner",
      email: "E-Mail",
      phone: "Telefon",
      alloy: "Legierung / Einsatz",
      qty: "Jahresmenge (kg)",
      length: "Stangenlänge (mm)",
      finish: "Oberfläche",
      message: "Zeichnungsnotiz / Toleranzen",
      submit: "Anfrage senden",
      successTitle: "Anfrage aufgenommen.",
      successBody:
        "In diesem Entwurf wird die Anfrage lokal gespeichert — kein Server. Inhaltlich ist das der Ablauf: Prüfung, Pressbarkeit, Werkzeugkosten, Termin.",
      another: "Weitere Anfrage",
      finishes: ["Walzblank / mill finish", "Eloxal natur", "Eloxal dunkel", "Pulver", "Bearbeitet, ohne Oberfläche"],
      countries: [
        "Deutschland",
        "Österreich",
        "Schweiz",
        "Niederlande",
        "Belgien",
        "Frankreich",
        "Italien",
        "Polen",
        "Tschechien",
        "Vereinigtes Königreich",
        "Irland",
        "Schweden",
        "Dänemark",
        "Spanien",
        "Andere EU",
      ],
    },
  },
  en: {
    brand: "AEXUM",
    brandSub: "Aluminium Extrusions",
    nav: {
      products: "Profiles",
      capabilities: "Capabilities",
      quality: "Quality",
      rfq: "RFQ",
    },
    topbar: "EU + UK  ·  EN 755 / EN 12020  ·  CE & UKCA",
    langDe: "DE",
    langEn: "EN",
    ctaPrimary: "Submit a drawing",
    ctaSecondary: "Presses & alloys",
    heroKicker: "Press plant · Göppingen  ·  UK desk · Birmingham",
    heroTitle: "Extruded aluminium for European industry.",
    heroLead:
      "Custom and catalogue 6xxx profiles. From die design to machined, finished bar — shipped across the EU and the United Kingdom.",
    stats: [
      { value: "48,000 t", label: "Annual capacity" },
      { value: "18–45 MN", label: "Four presses" },
      { value: "320 mm", label: "Circumscribed Ø" },
      { value: "14 m", label: "Max. bar length" },
    ],
    productsKicker: "Product families",
    productsTitle: "Profiles built for the machine — not the other way around.",
    productsLead:
      "Solid, hollow, T-slot and heatsink sections. Pressed to drawing or from stock in EN AW-6060 / 6063 / 6005A / 6082.",
    families: [
      {
        title: "Machine T-slot",
        body: "30 / 40 / 45 / 50 systems. Cut, deburr, tap, coat. Compatible with common modular frames.",
      },
      {
        title: "Structural hollows",
        body: "Box, round, multi-void. Walls from 1.2 mm. Frames, chassis, enclosures.",
      },
      {
        title: "Heatsinks & power electronics",
        body: "High surface-area finstock. 6060-T6 and 6101 on request.",
      },
      {
        title: "Custom dies",
        body: "Porthole and solid dies. First off-tool typically 8–12 weeks after die release.",
      },
    ],
    industriesKicker: "Sectors",
    industriesTitle: "Where aluminium has to carry load and hold tolerance.",
    industries: [
      { title: "Machinery & automation", body: "Frames, linear axes, guarding." },
      { title: "Commercial vehicles & rail", body: "Longitudinals, steps, roof bows." },
      { title: "Energy & e-mobility", body: "Battery trays, inverter housings, busbars." },
      { title: "Building & façade", body: "EN 15088, Qualanod / Qualicoat, EN 1090 EXC2." },
      { title: "Conveying", body: "Guides, sidewalls, roller tracks." },
      { title: "Medical & lab", body: "Clean alloys, batch documentation." },
    ],
    processKicker: "Process",
    processTitle: "From die to dispatch.",
    process: [
      { step: "01", title: "Tooling", body: "Flow simulation, in-house or partner die shop." },
      { step: "02", title: "Press", body: "6xxx billets. Stretch, straighten, age T5/T6." },
      { step: "03", title: "Machining", body: "CNC, punch, saw, tap, sub-assembly." },
      { step: "04", title: "Finish", body: "Anodise, powder, mechanical grind. Qualanod / Qualicoat." },
      { step: "05", title: "EU + UK freight", body: "CE and UKCA packs. Midlands consignment stock." },
    ],
    qualityKicker: "Evidence",
    qualityTitle: "What purchasing and quality actually ask for.",
    qualityLead:
      "3.1 mill certificates, heat traceability, VDA / PPAP first articles on request. Dual conformity packs for the EU and the UK.",
    certs: [
      "ISO 9001",
      "ISO 14001",
      "IATF 16949",
      "EN 15088",
      "EN 1090 EXC2",
      "EN 755 / EN 12020",
      "Qualanod",
      "Qualicoat",
      "CE / UKCA",
    ],
    logisticsTitle: "Europe and the UK, without a paperwork detour.",
    logisticsBody:
      "Post-Brexit we ship with separate declarations. UK kitting from Birmingham, EU direct from Göppingen. FCA, DAP or DDP against the frame contract.",
    finalCtaTitle: "Send the drawing. We will say if it will extrude.",
    finalCtaBody: "Engineering review within two working days. No brochure tennis.",
    footerNote: "AEXUM GmbH  ·  Press plant Göppingen  ·  UK desk Birmingham",
    footerLegal: "Design draft for industrial buyers. Not a public offer.",
    productsPage: {
      kicker: "Profiles & alloys",
      title: "What we press.",
      lead: "6xxx wrought alloys per EN 573. Dimensions and tolerances per EN 755-9, or EN 12020-2 for precision profiles.",
      alloysTitle: "Alloys",
      alloys: [
        { name: "EN AW-6060", temper: "T5 / T6", use: "Architectural, T-slot, anodising quality" },
        { name: "EN AW-6063", temper: "T5 / T6", use: "Thin-wall hollows, visible faces" },
        { name: "EN AW-6005A", temper: "T6", use: "Load-bearing frames, higher yield" },
        { name: "EN AW-6082", temper: "T6", use: "High-strength parts, chassis, machine beds" },
        { name: "EN AW-6101", temper: "T6 / T7", use: "Busbars, conductivity" },
      ],
      limitsTitle: "Process limits",
      limits: [
        { k: "Press force", v: "18 / 25 / 35 / 45 MN" },
        { k: "Circumscribed circle", v: "up to 320 mm" },
        { k: "Wall thickness", v: "from 1.2 mm, die-dependent" },
        { k: "Length", v: "up to 14,000 mm" },
        { k: "Mass per metre", v: "0.15–28 kg/m" },
        { k: "Lot size", v: "from ~300 kg repeat, 800 kg new die" },
      ],
    },
    capabilitiesPage: {
      kicker: "Capabilities",
      title: "More than the press.",
      lead: "Most buyers do not want three vendors for press, CNC and anodising. We keep the chain.",
      blocks: [
        {
          title: "Extrusion",
          body: "Four presses, in-house stretch, continuous ageing ovens T5 and T6. Billet stock in 6060, 6063, 6005A, 6082.",
        },
        {
          title: "Machining",
          body: "5-axis CNC, saw centres, punching, thread forming. Drawing parts with first-article packs.",
        },
        {
          title: "Surface",
          body: "Anodise EV1–C35, hard anodise, RAL powder, barrel grind. Qualanod and Qualicoat controlled.",
        },
        {
          title: "EU + UK logistics",
          body: "Weekly runs DACH, Benelux, northern Italy, Poland. UK: weekly groupage with UKCA set enclosed.",
        },
      ],
    },
    qualityPage: {
      kicker: "Quality & standards",
      title: "Measured, not claimed.",
      lead: "Calibrated gauges. Lab for hardness, conductivity, coating thickness. 3.1 certificates issued digitally.",
      items: [
        { title: "Dimensions", body: "EN 755-9. Optical cells at the saw. SPC on running series." },
        { title: "Material", body: "Spectrometer per heat. Homogenised billet, documented ageing." },
        { title: "Construction products", body: "EN 15088, DoP, UKCA equivalent for Great Britain." },
        { title: "Automotive", body: "IATF 16949, PPAP Level 3 on call, IMDS entries." },
      ],
    },
    rfqPage: {
      kicker: "RFQ",
      title: "Engineering enquiry.",
      lead: "No field maze. We need alloy or duty, rough geometry, volume, and ship-to country.",
      company: "Company",
      country: "Ship-to country",
      name: "Contact",
      email: "Email",
      phone: "Phone",
      alloy: "Alloy / duty",
      qty: "Annual volume (kg)",
      length: "Bar length (mm)",
      finish: "Finish",
      message: "Drawing notes / tolerances",
      submit: "Send enquiry",
      successTitle: "Enquiry captured.",
      successBody:
        "In this draft the enquiry is stored locally — no server. The real flow is review, extrudability, die cost, date.",
      another: "Another enquiry",
      finishes: ["Mill finish", "Natural anodise", "Dark anodise", "Powder", "Machined, no finish"],
      countries: [
        "Germany",
        "Austria",
        "Switzerland",
        "Netherlands",
        "Belgium",
        "France",
        "Italy",
        "Poland",
        "Czechia",
        "United Kingdom",
        "Ireland",
        "Sweden",
        "Denmark",
        "Spain",
        "Other EU",
      ],
    },
  },
} as const;

export type Copy = (typeof copy)[Lang];

export function useCopy(): Copy {
  const lang = useLang((s) => s.lang);
  return copy[lang];
}
