/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnfrageRouteImport } from './routes/anfrage'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as ProdukteRouteImport } from './routes/produkte'
import { Route as QualitaetRouteImport } from './routes/qualitaet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnfrageRoute = AnfrageRouteImport.update({
  id: '/anfrage',
  path: '/anfrage',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukteRoute = ProdukteRouteImport.update({
  id: '/produkte',
  path: '/produkte',
  getParentRoute: () => rootRouteImport,
} as any)
const QualitaetRoute = QualitaetRouteImport.update({
  id: '/qualitaet',
  path: '/qualitaet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anfrage': typeof AnfrageRoute
  '/leistungen': typeof LeistungenRoute
  '/produkte': typeof ProdukteRoute
  '/qualitaet': typeof QualitaetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anfrage': typeof AnfrageRoute
  '/leistungen': typeof LeistungenRoute
  '/produkte': typeof ProdukteRoute
  '/qualitaet': typeof QualitaetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anfrage': typeof AnfrageRoute
  '/leistungen': typeof LeistungenRoute
  '/produkte': typeof ProdukteRoute
  '/qualitaet': typeof QualitaetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/anfrage' | '/leistungen' | '/produkte' | '/qualitaet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anfrage' | '/leistungen' | '/produkte' | '/qualitaet'
  id: '__root__' | '/' | '/anfrage' | '/leistungen' | '/produkte' | '/qualitaet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnfrageRoute: typeof AnfrageRoute
  LeistungenRoute: typeof LeistungenRoute
  ProdukteRoute: typeof ProdukteRoute
  QualitaetRoute: typeof QualitaetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anfrage': {
      id: '/anfrage'
      path: '/anfrage'
      fullPath: '/anfrage'
      preLoaderRoute: typeof AnfrageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkte': {
      id: '/produkte'
      path: '/produkte'
      fullPath: '/produkte'
      preLoaderRoute: typeof ProdukteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualitaet': {
      id: '/qualitaet'
      path: '/qualitaet'
      fullPath: '/qualitaet'
      preLoaderRoute: typeof QualitaetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnfrageRoute: AnfrageRoute,
  LeistungenRoute: LeistungenRoute,
  ProdukteRoute: ProdukteRoute,
  QualitaetRoute: QualitaetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
